### ISSUE TITLE
minItems constraint not respected and causes invalid records to be deposited

### ISSUE THREAD

**Issue by edager** [Molecular-Biophysics-Database/mbdb-app#20]
Suppose we have an object with an array item of this form (oarepo schema) :

```yaml
record_information:
  properties:
    title:
      type: keyword
      help.en: Short descriptive title of the record
      required: true
    keywords[]:
      ^minItems: 2
      ^help.en: List of keywords describing this particular record content,
        e.g. antibody, epitope, ligand optimization, SARS-CoV-2, agonist, antagonist,
        HIV, etc.
      ^required: true
      type: keyword
```
The following two cases should fail validation, and should not be loaded into the database.

```json
"record_information":
  "title": "Invalid object"
  "keywords": []
```

```json
"record_information":
  "title": "Another invalid object"
  "keywords": ["OneTooFew"]
```

However, both can be loaded without problems, and furthermore leaves out the (required) array item from the record

```json
"record_information":
  "title": "Invalid object"
```

```json
"record_information":
  "title": "Another invalid object"
```
